const corePages=[
{id:"story",title:"Product overview",group:"Product"},{id:"landings",title:"All landing pages",group:"Product"},{id:"competitors",title:"Whole-market pricing",group:"Market"},{id:"diallers",title:"Diallers",group:"Market"},{id:"outbound",title:"Outbound email",group:"Market"},{id:"marketing",title:"Marketing centres",group:"Market"},{id:"crm",title:"CRM",group:"Market"},{id:"work",title:"Work management",group:"Market"},{id:"pricing",title:"forwardslash.ch pricing",group:"Decisions"},{id:"decisions",title:"Product decisions",group:"Decisions"},{id:"sources",title:"Sources and method",group:"Decisions"}
];
const scripts=[
["From research to revenue","Finding customers should not mean stitching together ten different tools. forwardslash.ch helps you research a market, build a precise list, design a campaign and reach people by email, SMS or phone. Replies, calls and bookings stay connected to the same contact. Run an event, manage guests and sign-ups, share an online booking page, then follow every opportunity through to the meeting and the sale. One calm workspace shows what is happening, what needs attention and what was delivered without losing the relationship. Start with one useful list. Grow from there."],
["One campaign, properly run","A good campaign begins before the first message. In forwardslash.ch, research the market, define the audience and build a clean contact list. Shape the offer, write the email, plan the calls and prepare the SMS follow-up. Review the audience, message, timing and cost before anything runs. Then manage replies, call outcomes, meeting bookings and next steps in one place. You can see which activity created a real conversation and which conversations became sales, with everyone clearly understanding the outcome. Thoughtful planning. Controlled execution. Clear results. Build your first campaign free."],
["Events that continue","An event is more than a registration page. forwardslash.ch helps you research the right guests, build the invitation list and send thoughtful email or SMS. Track sign-ups, questions, dietary needs and attendance without losing the relationship behind each name. Share booking pages for private meetings before or after the event. Give your team a clear call list for important guests. When the event ends, follow replies, meetings and opportunities through to the work delivered without losing context. One guest list becomes a complete relationship programme. Start with your next event."],
["The sales day, connected","Your sales day should not disappear between tabs. forwardslash.ch brings research, contacts, email, calling, SMS and meeting bookings into one focused workspace. Begin with the people who matter. See the reason for every call, the last message and the right next action. Send the promised follow-up while the conversation is fresh. Share your booking page and keep the meeting connected to the campaign that created it. Managers see progress without chasing updates. Delivery receives the full customer context. Spend less time moving information. Spend more time moving relationships forward together."],
["From first contact to delivery","Most systems stop when the deal is won. forwardslash.ch keeps going. Research and build the audience. Run email, SMS and calling campaigns with clear approvals and limits. Capture replies, schedule meetings and manage the opportunity without losing the original context. When the customer says yes, turn the promise into a project with owners, tasks and dates. Sales can see delivery. Delivery can see the relationship. Leadership can see what created demand and what produced a result. From first contact to finished work, the whole story stays clearly connected. Start free."]
];
const landingPages=[
["01","The quiet system","From first contact to finished work.","landing/01-quiet-system.html","landing/quiet"],["02","Upload a list","Import, review, research and act.","landing/02-upload-a-list.html","landing/upload"],["03","Start with one action","Email, list or project.","landing/03-start-with-one-action.html","landing/action"],["04","No seat tax","Unlimited Business collaborators.","landing/04-no-seat-tax.html","landing/no-seat-tax"],["05","European control","Privacy, portability and restraint.","landing/05-european-control.html","landing/europe"],["06","Agency approval","Client-safe campaign review.","landing/06-agency-approval.html","landing/agency"],["07","Campaign to delivery","Keep the promise connected.","landing/07-campaign-to-delivery.html","landing/delivery"],["08","Calling workspace","Contextual calling economics.","landing/08-calling-workspace.html","landing/calling"],["09","Replace the stack","Replace one seam at a time.","landing/09-replace-the-stack.html","landing/stack"],["10","Personal to company","Start personally, transfer later.","landing/10-personal-to-company.html","landing/personal"],["P","Pricing comparison","Full feature and usage matrix.","landing/pricing-comparison.html","landing/pricing"],["B","Editorial library","Nine conversion-led articles.","blog/index.html","surface/blog"],["V","Script studio","Five scripts, 30 starts and 30 calls to action.","scripts/explainer-script-studio.html","surface/scripts"]
];
const catMap={diallers:"Diallers",outbound:"Outbound email",marketing:"Marketing",crm:"CRM",work:"Work management"};
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const header=(k,t,l)=>`<header class="hero"><div class="wrap"><div class="eyebrow">${k}</div><h1>${t}</h1><p class="lede">${l}</p></div></header>`;
function extras(v){const s=(v.cat+" "+v.model+" "+v.use).toLowerCase();if(v.cat==="Diallers")return"Telephone numbers, minutes, international destinations, SMS, recording, transcription and AI may be separate.";if(v.cat==="Outbound email")return"Sending mailboxes, domains, verification, warm-up infrastructure, stored contacts and overage may be separate.";if(v.cat==="Marketing")return"Contact tiers, monthly send volume, SMS, extra seats, onboarding and automation limits commonly change the bill.";if(v.cat==="CRM")return"Extra seats, calling, marketing contacts, automation, AI credits, implementation and support can increase the total.";return"Paid members, guests, storage, AI, automation, portfolio features and annual minimums can change the total."}
function table(list,category=true){return`<div class="tablewrap"><table class="comparison"><thead><tr><th>Company</th>${category?"<th>Area</th>":""}<th>Public price</th><th>How charged</th><th>What you get</th><th>Likely extras</th><th>Europe evidence</th><th>Source</th></tr></thead><tbody>${list.map(v=>`<tr data-id="${v.id}" tabindex="0"><td><strong>${esc(v.name)}</strong><small>Select for full breakdown →</small></td>${category?`<td>${esc(v.cat)}</td>`:""}<td><strong>${esc(v.price)}</strong></td><td>${esc(v.model)}</td><td>${esc(v.use)}</td><td>${esc(extras(v))}</td><td>${v.share==null?"Not disclosed":esc(v.share)+"%"}<small>${esc(v.confidence)}</small></td><td><a class="source-inline" href="${v.source}" target="_blank" onclick="event.stopPropagation()">Live pricing ↗</a></td></tr>`).join("")}</tbody></table></div>`}
function breakout(v){return`<aside class="breakout" id="breakout"><div class="eyebrow">Selected competitor · ${esc(v.cat)}</div><h2>${esc(v.name)}</h2><div class="breakout-price">${esc(v.price)}</div><p class="source-note">Public pricing summary. Check the linked vendor page before making a purchasing or pricing decision.</p><dl><div><dt>How the bill scales</dt><dd>${esc(v.model)}</dd></div><div><dt>What the offer is for</dt><dd>${esc(v.use)}</dd></div><div><dt>What may sit outside the headline price</dt><dd>${esc(extras(v))}</dd></div><div><dt>European position</dt><dd>${esc(v.eu)}</dd></div><div><dt>Evidence label</dt><dd>${esc(v.confidence)}</dd></div></dl><div class="actions"><a class="btn dark" href="#competitor/${v.id}">Full pricing page →</a><a class="btn" href="${v.source}" target="_blank">See the evidence ↗</a></div><p class="arrow-help">Use ← and → to move through every full competitor pricing page.</p></aside>`}
function renderStory(){return`${header("forwardslash.ch product book","Find. Reach. Meet. Deliver.","Research markets, build lists, run email, SMS and calling campaigns, arrange events and bookings, then carry the customer promise through sales and delivery.")}<section class="section black"><div class="wrap">${scripts.map((s,i)=>`<article class="script"><span class="tag">Script ${i+1} · 90 words</span><h3>${s[0]}</h3><p>${s[1]}</p></article>`).join("")}<div class="actions"><a class="btn light" href="#surface/scripts">Open the script studio in this viewer</a></div></div></section>`}
function renderLandings(){return`${header("One continuous viewer","All landing pages.","Every page opens inside this screen. The permanent menu and left/right controls stay visible.")}<section class="section"><div class="wrap"><div class="tablewrap"><table><thead><tr><th>No.</th><th>Page</th><th>Purpose</th><th></th></tr></thead><tbody>${landingPages.map(x=>`<tr><td>${x[0]}</td><td><strong>${x[1]}</strong></td><td>${x[2]}</td><td><a href="#${x[4]}">View here →</a></td></tr>`).join("")}</tbody></table></div></div></section>`}
function renderCompetitors(){return`${header(`28 competitors · checked ${checked}`,"The whole market on one page.","The market remains visible on the left. Select a company and its pricing, inclusions, extra-cost risks, European evidence and direct source stay open in the frame on the right.")}<section class="market-section"><div class="market-tools"><input id="search" placeholder="Search the whole market"><select id="category"><option value="all">All five areas</option>${Object.values(catMap).map(x=>`<option>${x}</option>`).join("")}</select></div><div class="market-frame"><div id="comparison" class="market-table">${table(vendors)}</div><div id="breakoutHost" class="breakout-host">${breakout(vendors[0])}</div></div></section>`}
function renderCategory(id){const cat=catMap[id],list=vendors.filter(v=>v.cat===cat);return`${header(`${list.length} competitors`,cat,"Compare the category on the left. Keep a selected company's evidence-backed pricing breakdown open on the right.")}<section class="market-section"><div class="market-frame"><div class="market-table">${table(list,false)}</div><div id="breakoutHost" class="breakout-host">${breakout(list[0])}</div></div></section>`}
function renderPricing(){return`${header("A pricing recommendation, not vague possibilities","How forwardslash.ch can sit in this market.","Start with a complete collaborative workspace. Charge separately only where the marginal supplier cost or specialist operator value is real.")}<section class="section"><div class="wrap"><div class="price-summary"><article><span>Personal</span><h2>Free</h2><p>3 members, 2,500 records, own-mailbox email and 3 active projects.</p></article><article><span>Business workspace</span><h2>A$249/month</h2><p>Unlimited collaborators, 100,000 records, unlimited projects, shared CRM, campaigns, approvals, reporting and API.</p></article><article><span>Campaign operator</span><h2>A$59/operator</h2><p>Bulk lists, sequences, schedules, suppression, deliverability controls and higher-volume execution.</p></article><article><span>Calling operator</span><h2>A$79/operator</h2><p>Dial queues, click-to-call, dispositions, reporting and controls. Numbers and usage remain visible.</p></article></div><h2 class="pricing-heading">Alternative structures to test</h2>${pricingOptions.map(o=>`<div class="option"><div><span class="tag">${o.name}</span><h3>${o.title}</h3></div><p>${o.body}<br><span class="small">${o.fit}</span></p><strong>${o.price}</strong></div>`).join("")}</div></section>`}
function renderDecisions(){const x=[["Business must be complete","A$249 should fund CRM, inbox, campaigns, approvals, projects, reporting and API for unlimited collaborators."],["Campaign licence","Bulk audiences, sequences, scheduling, suppression, deliverability and controlled execution."],["Calling licence","Click-to-call, queues, dispositions, controls and reporting. Numbers and minutes remain visible."],["European restraint","Make privacy and residency claims only when operationally proven."],["Comparable evidence","Do not combine country, global and historical share proxies."],["Test real bills","Model a solo user, 12-person firm, agency and high-volume operator."]];return`${header("What the research means","Decisions before publication.","Broad collaboration without a seat tax, paired with clear specialist and supplier costs.")}<section class="section"><div class="wrap grid2">${x.map(a=>`<article class="card"><h3>${a[0]}</h3><p>${a[1]}</p></article>`).join("")}</div></section>`}
function renderSources(){return`${header("Research method","Sources and limits.","Pricing changes often. Primary vendor pages support prices; evidence labels explain market-position data.")}<section class="section"><div class="wrap detail"><div class="note"><strong>Market-share warning.</strong> Europe-only shares are rarely public. Estimates, country studies and global proxies are not the same measure.</div><div class="source-list">${sources.map(s=>`<a href="${s.url}" target="_blank">${s.name} ↗</a>`).join("")}</div></div></section>`}
function renderVendor(v){return`<div class="wrap detail"><header class="detail-head"><div class="eyebrow">${esc(v.cat)} · pricing page ${vendors.indexOf(v)+1} of ${vendors.length}</div><h1>${esc(v.name)}</h1><div class="detail-price">${esc(v.price)}</div><p class="lede">${esc(v.use)}</p></header><div class="pricing-breakdown"><section><span>How it is charged</span><h3>${esc(v.model)}</h3></section><section><span>What you get</span><p>${esc(v.use)}</p></section><section><span>What else may cost</span><p>${esc(extras(v))}</p></section><section><span>European market evidence</span><p>${esc(v.eu)} <em>${esc(v.confidence)}</em></p></section></div><div class="actions"><a class="btn dark" href="${v.source}" target="_blank">Check live pricing ↗</a><a class="btn" href="#competitors">Whole-market table</a></div><section class="section"><h2>Questions for a real quote.</h2><div class="grid2"><article class="card"><h3>At our team size</h3><p>What is the monthly and annual total for all required users, workspaces and permissions?</p></article><article class="card"><h3>At our volume</h3><p>What do contacts, sends, minutes, numbers, SMS, storage and AI cost at realistic use?</p></article></div></section></div>`}
function renderEmbed(x){return`<section class="embedded"><div class="embedbar"><div><span>${x[0]}</span><strong>${x[1]}</strong></div><span>${x[2]}</span><a href="${x[3]}" target="_blank">Open separately ↗</a></div><iframe title="${esc(x[1])}" src="${x[3]}"></iframe></section>`}
const renderer={story:renderStory,landings:renderLandings,competitors:renderCompetitors,diallers:()=>renderCategory("diallers"),outbound:()=>renderCategory("outbound"),marketing:()=>renderCategory("marketing"),crm:()=>renderCategory("crm"),work:()=>renderCategory("work"),pricing:renderPricing,decisions:renderDecisions,sources:renderSources};
const landingSequence=landingPages.map(x=>({id:x[4],title:x[1],group:"Landing pages",kind:"embed",item:x}));
const vendorSequence=vendors.map(v=>({id:`competitor/${v.id}`,title:v.name,group:"Competitor pricing",kind:"vendor",vendor:v}));
const sequence=[...corePages.slice(0,2),...landingSequence,...corePages.slice(2,8),...vendorSequence,...corePages.slice(8)];
const rail=document.getElementById("rail");let group="";
sequence.forEach((p,i)=>{if(p.group!==group){const d=document.createElement("div");d.className="rail-label rail-group";d.textContent=p.group;rail.appendChild(d);group=p.group}const b=document.createElement("button");b.dataset.page=p.id;b.innerHTML=`<span>${String(i+1).padStart(2,"0")}</span><span>${p.title}</span>`;b.onclick=()=>location.hash="#"+p.id;rail.appendChild(b)});
let current=0;
function attachRows(){document.querySelectorAll("tr[data-id]").forEach(row=>{const open=()=>{const v=vendors.find(x=>x.id===row.dataset.id);document.querySelectorAll("tr[data-id]").forEach(x=>x.classList.toggle("selected",x===row));document.getElementById("breakoutHost").innerHTML=breakout(v)};row.onclick=open;row.onkeydown=e=>{if(e.key==="Enter")open()}})}
function attachSearch(){const q=document.getElementById("search"),c=document.getElementById("category");const update=()=>{const s=q.value.toLowerCase(),cat=c.value;document.getElementById("comparison").innerHTML=table(vendors.filter(v=>(cat==="all"||v.cat===cat)&&`${v.name} ${v.cat} ${v.price} ${v.model} ${v.use}`.toLowerCase().includes(s)));attachRows()};q.oninput=update;c.onchange=update}
function route(){const raw=location.hash.slice(1)||"story",idx=sequence.findIndex(p=>p.id===raw);current=idx<0?0:idx;const p=sequence[current];document.getElementById("content").innerHTML=p.kind==="embed"?renderEmbed(p.item):p.kind==="vendor"?renderVendor(p.vendor):(renderer[p.id]||renderStory)();document.getElementById("dockTitle").textContent=`${current+1} / ${sequence.length} · ${p.title}`;document.querySelectorAll("#rail button").forEach(b=>b.classList.toggle("active",b.dataset.page===p.id));document.querySelector("#rail button.active")?.scrollIntoView({block:"nearest"});if(p.id==="competitors")attachSearch();attachRows();window.scrollTo({top:0})}
document.getElementById("prev").onclick=()=>location.hash="#"+sequence[(current-1+sequence.length)%sequence.length].id;document.getElementById("next").onclick=()=>location.hash="#"+sequence[(current+1)%sequence.length].id;document.getElementById("down").onclick=()=>window.scrollBy({top:innerHeight*.82,behavior:"smooth"});document.addEventListener("keydown",e=>{if(e.target.matches("input,select"))return;if(e.key==="ArrowLeft")document.getElementById("prev").click();if(e.key==="ArrowRight")document.getElementById("next").click();if(e.key==="ArrowDown")document.getElementById("down").click()});addEventListener("hashchange",route);route();
