const checked="23 July 2026";
const vendors=[
{id:"aircall",name:"Aircall",cat:"Diallers",region:"France / global",price:"Quote; 3-seat minimum",model:"Per licence + usage",use:"Cloud phone, sales and support calls; Professional adds Power Dialer and advanced analytics.",eu:"Strong European-origin vendor; exact Europe share not public.",share:null,confidence:"not disclosed",source:"https://aircall.io/pricing/"},
{id:"cloudtalk",name:"CloudTalk",cat:"Diallers",region:"Slovakia / global",price:"€19–€49 user/month annual",model:"Per user + regional usage",use:"Starter through Expert; EU domestic bundles differ from cross-border calls.",eu:"European-origin vendor with EU regional bundles; exact product share not public.",share:null,confidence:"not disclosed",source:"https://www.cloudtalk.io/pricing/"},
{id:"justcall",name:"JustCall",cat:"Diallers",region:"US / global",price:"From about $29 user/month",model:"Per user + calling/SMS",use:"Business phone, sales dialler, SMS and conversation intelligence.",eu:"European customer presence; no credible public Europe-only share located.",share:null,confidence:"not disclosed",source:"https://justcall.io/pricing/"},
{id:"ringover",name:"Ringover",cat:"Diallers",region:"France / Europe",price:"Public tiers vary by market",model:"Per user + usage",use:"Voice, video, SMS and contact-centre workflows; European-headquartered alternative.",eu:"French vendor with strong regional relevance; exact Europe share not public.",share:null,confidence:"not disclosed",source:"https://www.ringover.com/pricing"},
{id:"dialpad",name:"Dialpad",cat:"Diallers",region:"US / global",price:"From about $15 user/month",model:"Per user + add-ons",use:"Business communications with calling, meetings and AI conversation tools.",eu:"Global vendor; no dependable Europe product-share figure found.",share:null,confidence:"not disclosed",source:"https://www.dialpad.com/pricing/"},
{id:"instantly",name:"Instantly",cat:"Outbound email",region:"US / global",price:"$47/month Growth",model:"Volume, not seats",use:"Unlimited sending accounts and warm-up; plan scales by uploaded contacts and emails.",eu:"Used globally; exact Europe share unavailable.",share:null,confidence:"not disclosed",source:"https://instantly.ai/pricing"},
{id:"smartlead",name:"Smartlead",cat:"Outbound email",region:"US / global",price:"$39 / $94 / $174 / $379",model:"Contact and send capacity",use:"Unlimited email accounts; Base includes 2,000 contacts and 6,000 sends monthly.",eu:"Global outbound tool; no credible Europe-only share published.",share:null,confidence:"not disclosed",source:"https://www.smartlead.ai/pricing"},
{id:"lemlist",name:"lemlist",cat:"Outbound email",region:"France / global",price:"Email, Multichannel, Enterprise",model:"Plan + seats + credits",use:"Lead database, email, LinkedIn, phone data, warm-up and multichannel sequences.",eu:"French-origin vendor with high European relevance; exact share not public.",share:null,confidence:"not disclosed",source:"https://www.lemlist.com/pricing?lang=en"},
{id:"woodpecker",name:"Woodpecker",cat:"Outbound email",region:"Poland / global",price:"From $35/month",model:"Contacted + stored prospects",use:"Cold email and agency workflows; lowest tier 500 contacted and 2,000 stored prospects.",eu:"Polish public company; exact Europe category share not public.",share:null,confidence:"not disclosed",source:"https://woodpecker.co/pricing/"},
{id:"mailshake",name:"Mailshake",cat:"Outbound email",region:"US / global",price:"From about $29 user/month",model:"Per sender/user",use:"Email outreach, sequences, lead catcher and sales engagement.",eu:"Global tool; no Europe-only share published.",share:null,confidence:"not disclosed",source:"https://mailshake.com/pricing/"},
{id:"brevo",name:"Brevo",cat:"Marketing",region:"France / Europe",price:"$0 / $9 / $18 / $499+",model:"Email volume",use:"Marketing and transactional email, SMS, WhatsApp, automation, CRM and landing pages.",eu:"A European leader; reported 67% detected use among French companies sending marketing email in one 2026 study.",share:67,confidence:"country proxy",source:"https://www.brevo.com/pricing/"},
{id:"mailchimp",name:"Mailchimp",cat:"Marketing",region:"US / global",price:"$0 / $13 / $20 / $350+",model:"Contacts + sends",use:"Email marketing, automations, forms, landing pages and analytics.",eu:"Reported 21% detected use in the same French email-company sample; UK segment figures vary widely.",share:21,confidence:"country proxy",source:"https://mailchimp.com/pricing/marketing/"},
{id:"hubspot-marketing",name:"HubSpot Marketing Hub",cat:"Marketing",region:"US / global",price:"Starter; Pro about $890; Enterprise about $3,600",model:"Tier + contacts + seats + credits",use:"Marketing automation, email, forms, ads, attribution and customer-platform integration.",eu:"Strong B2B presence; global domain-detection proxy about 7.76%, not Europe market share.",share:7.76,confidence:"global proxy",source:"https://www.hubspot.com/pricing/marketing"},
{id:"activecampaign",name:"ActiveCampaign",cat:"Marketing",region:"US / global",price:"Contact-based; calculate quote",model:"Contacts + tier",use:"Email marketing, automation, segmentation and CRM-adjacent workflows.",eu:"Meaningful European use; no reliable public Europe-only share located.",share:null,confidence:"not disclosed",source:"https://www.activecampaign.com/pricing"},
{id:"klaviyo",name:"Klaviyo",cat:"Marketing",region:"US / global",price:"Free then contact/message volume",model:"Profiles + messages",use:"Ecommerce email, SMS, customer data and revenue attribution.",eu:"Strong ecommerce position; global marketing-automation detection proxy about 9.43%.",share:9.43,confidence:"global proxy",source:"https://www.klaviyo.com/pricing"},
{id:"salesforce",name:"Salesforce",cat:"CRM",region:"US / global",price:"From $25 user/month; enterprise tiers higher",model:"Per user + clouds + usage",use:"Enterprise CRM ecosystem spanning sales, service, marketing, analytics and platform.",eu:"One research estimate puts European cloud CRM share around 23%; IDC reports 20% worldwide CRM share for 2025.",share:23,confidence:"reported estimate",source:"https://www.salesforce.com/sales/pricing/"},
{id:"hubspot-sales",name:"HubSpot Sales Hub",cat:"CRM",region:"US / global",price:"Starter then paid sales seats",model:"Seats + credits + other hubs",use:"Smart CRM, pipeline, sequences, calling, automation and sales analytics.",eu:"Large European B2B presence, but no credible product-level Europe share published.",share:null,confidence:"not disclosed",source:"https://www.hubspot.com/pricing/sales"},
{id:"pipedrive",name:"Pipedrive",cat:"CRM",region:"Estonia / global",price:"Lite, Growth, Premium, Ultimate",model:"Per seat + add-ons",use:"Pipeline-first CRM; add-ons include lead generation, campaigns and projects.",eu:"European-origin CRM with strong SMB recognition; exact Europe share not public.",share:null,confidence:"not disclosed",source:"https://www.pipedrive.com/en/pricing"},
{id:"close",name:"Close",cat:"CRM",region:"US / global",price:"$19 / $49 / $109 / $149 monthly",model:"Per user",use:"Sales CRM with email, calling, SMS, automation and high-volume dialling in higher tiers.",eu:"Primarily sales-team niche; no public Europe-only market share.",share:null,confidence:"not disclosed",source:"https://close.com/pricing"},
{id:"zoho",name:"Zoho CRM",cat:"CRM",region:"India / global",price:"Free then roughly €14–€52 user/month",model:"Per user / suite option",use:"Broad configurable CRM connected to the large Zoho business-software suite.",eu:"Broad European SMB presence; exact current Europe share not publicly verified.",share:null,confidence:"not disclosed",source:"https://www.zoho.com/crm/zohocrm-pricing.html"},
{id:"dynamics",name:"Microsoft Dynamics 365 Sales",cat:"CRM",region:"US / global",price:"From about €60 user/month",model:"Per user + Microsoft stack",use:"Enterprise sales CRM integrated with Microsoft 365, Power Platform and Azure.",eu:"Microsoft is a major European CRM provider; product-level Europe share varies by measure.",share:5.9,confidence:"global legacy proxy",source:"https://www.microsoft.com/en-us/dynamics-365/pricing"},
{id:"clickup",name:"ClickUp",cat:"Work management",region:"US / global",price:"Free; paid from about $7 user/month annual",model:"Per member + AI",use:"Tasks, docs, goals, dashboards, time, chat and automations in an everything-work position.",eu:"No robust Europe share; global spend/adoption proxy ranks it behind Jira, Notion and Asana.",share:null,confidence:"global rank proxy",source:"https://clickup.com/pricing"},
{id:"asana",name:"Asana",cat:"Work management",region:"US / global",price:"Free / $10.99 / $24.99 annual",model:"Per user + AI credits",use:"Projects, portfolios, goals, workload, approvals and cross-functional work management.",eu:"No Europe-only share; global adoption proxy around 20% in one spend dataset.",share:20,confidence:"global proxy",source:"https://asana.com/pricing"},
{id:"monday",name:"monday.com",cat:"Work management",region:"Israel / global",price:"Free; paid tiers, 3-seat minimum",model:"Seat buckets + product",use:"Configurable boards across work management, CRM and software development.",eu:"No Europe-only share; global adoption proxy around 15% in one spend dataset.",share:15,confidence:"global proxy",source:"https://monday.com/pricing/"},
{id:"jira",name:"Jira",cat:"Work management",region:"Australia / global",price:"Free / Standard / Premium / Enterprise",model:"Per user, tiered",use:"Issue, software and work tracking with automation, reporting and Atlassian ecosystem.",eu:"Historic Germany technology share reported 46.3%; a global spend proxy shows 50% adoption. Neither is current Europe-wide share.",share:46.3,confidence:"historic country proxy",source:"https://www.atlassian.com/software/jira/pricing"},
{id:"notion",name:"Notion",cat:"Work management",region:"US / global",price:"Free; Plus about $10; Business about $20 user/month",model:"Per member + AI",use:"Docs, wikis, databases, projects, forms and increasingly integrated knowledge work.",eu:"No Europe-only share; global adoption proxy around 32% in one spend dataset.",share:32,confidence:"global proxy",source:"https://www.notion.com/pricing"},
{id:"basecamp",name:"Basecamp",cat:"Work management",region:"US / global",price:"Per-user or fixed organisation plan",model:"Seat or fixed workspace",use:"Projects, message boards, to-dos, files, schedule and client collaboration.",eu:"No reliable Europe-only share published.",share:null,confidence:"not disclosed",source:"https://basecamp.com/pricing"},
{id:"teamwork",name:"Teamwork",cat:"Work management",region:"Ireland / global",price:"Free then per user",model:"Per user + client work",use:"Project management focused on agencies and client delivery, time and profitability.",eu:"Irish vendor with European relevance; exact share not public.",share:null,confidence:"not disclosed",source:"https://www.teamwork.com/pricing/"}
];
const sources=[
{name:"CloudTalk pricing and EU calling packages",url:"https://help.cloudtalk.io/en/articles/13130387-understanding-pricing-plans-and-what-they-include"},
{name:"Aircall pricing",url:"https://aircall.io/pricing/"},{name:"Smartlead pricing",url:"https://www.smartlead.ai/pricing"},{name:"Instantly pricing",url:"https://instantly.ai/pricing"},{name:"lemlist pricing",url:"https://www.lemlist.com/pricing?lang=en"},{name:"Woodpecker billing model",url:"https://woodpecker.co/help-center/en/articles/5234070-billing-faq"},{name:"Close pricing",url:"https://close.com/pricing"},{name:"HubSpot Sales pricing",url:"https://www.hubspot.com/pricing/sales"},{name:"HubSpot Marketing pricing",url:"https://www.hubspot.com/pricing/marketing"},{name:"Asana pricing",url:"https://asana.com/pricing"},{name:"monday.com pricing",url:"https://monday.com/pricing/"},{name:"ClickUp pricing",url:"https://clickup.com/pricing"},{name:"Salesforce IDC market-share statement",url:"https://www.salesforce.com/news/stories/idc-crm-market-share-ranking-2026/"},{name:"European cloud CRM market estimate",url:"https://www.emergenresearch.com/industry-report/europe-cloud-crm-market/executive-summary"},{name:"Marketing automation detection research",url:"https://bloomberry.com/blog/the-state-of-marketing-automation-tools-in-2026/"},{name:"Project-management adoption proxy",url:"https://ramp.com/vendors/categories/project-management"}
];
const pricingOptions=[
{name:"Option A",title:"Workspace-first",price:"Free / A$249 Business",body:"Unlimited Business collaborators. Campaign A$59 and Calling A$89 per operator. Research, AI and carrier costs metered.",fit:"Strongest match to the current product thesis."},
{name:"Option B",title:"Lower base, higher operators",price:"A$149 + A$89/A$119",body:"Easier company entry, but more value must move into specialist licences. Risks confusing ordinary sales activity with paid acceleration.",fit:"Useful if A$249 blocks early small teams."},
{name:"Option C",title:"Three workspace tiers",price:"A$0 / A$199 / A$499",body:"Business and Scale workspaces with included operator allowances. Easier enterprise ladder, less clean economic separation.",fit:"Useful once portfolio and governance features exist."},
{name:"Option D",title:"Per active operator",price:"A$39–A$129 per operator",body:"Unlimited viewers but charges each active CRM/sales user. Familiar to buyers, yet recreates some seat-tax behaviour.",fit:"Best only if workspace willingness-to-pay proves weak."},
{name:"Option E",title:"Usage-led platform",price:"A$99 base + consumption",body:"Low base with email, call, research and AI wallets. Very transparent but revenue becomes variable and harder to forecast.",fit:"Potential agency or campaign-specific edition."},
{name:"Option F",title:"Agency master account",price:"A$399+ + client packs",body:"Master reporting, separated client workspaces, client approvers and pooled campaign operators. Provider use allocated to clients.",fit:"Strong vertical package after multi-client controls are live."}
];
